# Site
title:              First Page
bio:                'Lorem ipsum dolor sit amet'
description:        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             it_IT
url:                http://127.0.0.1:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:

github-url:         ''
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           ''
#xing:              username
instagram:          ''
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
youtube:            ''
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
flickr:             ''
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
